kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: billing
  name: billing
  namespace: api
spec:
  type: NodePort
  ports:
    - name: api
      port: 5000
      targetPort: 5000
  selector:
    k8s-app: billing

---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: billing
  name: billing
  namespace: api
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: billing
  template:
    metadata:
      labels:
        k8s-app: billing
    spec:
      containers:
        - name: billing
          image: billingcore:1.0
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          ports:
            - containerPort: 5000
              protocol: TCP
              name: api
      nodeSelector:
        "kubernetes.io/os": linux
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
          