version: '3'

services:
  bitbucket:
    image: "atlassian/bitbucket-server:7.9.0"
    container_name: bitbucket
    restart: always
    ports:
      - "7990:7990"
      - "7999:7999"
    environment:
      - BITBUCKET_HOME=/var/atlassian/application-data/bitbucket/
    volumes:
      - ./bitbucket-data:/var/atlassian/application-data/bitbucket

volumes:
  bitbucket-data:
    external:
      name: bitbucket-data