apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-pv
  namespace: service
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /home/admin/service-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - u20-dev-test03

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-pvc
  namespace: service
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: service
data:
  rabbitmq.conf: |
    loopback_users.guest = false
    listeners.tcp.default = 5672
    management.tcp.port = 15672
  
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_shovel_management,rabbitmq_prometheus].
    
---

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: rabbitmq
  name: rabbitmq
  namespace: service
spec:
  type: NodePort
  ports:
    - name: gateway
      port: 5672
      targetPort: 5672
      nodePort: 30072
      protocol: TCP
    - name: ui
      port: 15672
      targetPort: 15672
      nodePort: 30073
      protocol: TCP
    - name: metrics
      port: 15692
      targetPort: 15692
      nodePort: 30074
      protocol: TCP
  selector:
    k8s-app: rabbitmq

---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: rabbitmq
  name: rabbitmq
  namespace: service
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: rabbitmq
  template:
    metadata:
      labels:
        k8s-app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_USE_LONGNAME
              value: "true"
            - name: RABBITMQ_NODENAME
              value: "rabbit@localhost"
          ports:
            - containerPort: 5672
              protocol: TCP
              name: gateway
            - containerPort: 15672
              protocol: TCP
              name: ui
            - containerPort: 15692
              protocol: TCP
              name: metrics
          volumeMounts:
            - name: rabbitmq-vol
              mountPath: /var/lib/rabbitmq
              subPath: rabbitmq
            - name: rabbitmq-conf
              mountPath: /etc/rabbitmq
      volumes:
      - name: rabbitmq-vol
        persistentVolumeClaim:
          claimName: service-pvc
      - name: rabbitmq-conf
        configMap:
          name: rabbitmq-config
      nodeSelector:
        "kubernetes.io/hostname": u20-dev-test03
        